name: Verification
on:
  pull_request:
    branches:
      - main
jobs:
  markdown-link-check:
    name: Link check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          folder-path: "docs"
          file-path: "./README.md"
          check-modified-files-only: "yes"
          base-branch: "main"
  markdown-lint:
    name: Markdown lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://tmknom/markdownlint:0.23.1
        with:
          args: /github/workspace
  mkdocs-lint:
    name: mkdocs build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://squidfunk/mkdocs-material:6.1.4
        with:
          args: build --strict -f /github/workspace/mkdocs.yml